// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "KrishiSevak.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



KrishiSevak::ServiceKrishiSevak_ptr KrishiSevak::ServiceKrishiSevak_Helper::_nil() {
  return ::KrishiSevak::ServiceKrishiSevak::_nil();
}

::CORBA::Boolean KrishiSevak::ServiceKrishiSevak_Helper::is_nil(::KrishiSevak::ServiceKrishiSevak_ptr p) {
  return ::CORBA::is_nil(p);

}

void KrishiSevak::ServiceKrishiSevak_Helper::release(::KrishiSevak::ServiceKrishiSevak_ptr p) {
  ::CORBA::release(p);
}

void KrishiSevak::ServiceKrishiSevak_Helper::marshalObjRef(::KrishiSevak::ServiceKrishiSevak_ptr obj, cdrStream& s) {
  ::KrishiSevak::ServiceKrishiSevak::_marshalObjRef(obj, s);
}

KrishiSevak::ServiceKrishiSevak_ptr KrishiSevak::ServiceKrishiSevak_Helper::unmarshalObjRef(cdrStream& s) {
  return ::KrishiSevak::ServiceKrishiSevak::_unmarshalObjRef(s);
}

void KrishiSevak::ServiceKrishiSevak_Helper::duplicate(::KrishiSevak::ServiceKrishiSevak_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

KrishiSevak::ServiceKrishiSevak_ptr
KrishiSevak::ServiceKrishiSevak::_duplicate(::KrishiSevak::ServiceKrishiSevak_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

KrishiSevak::ServiceKrishiSevak_ptr
KrishiSevak::ServiceKrishiSevak::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


KrishiSevak::ServiceKrishiSevak_ptr
KrishiSevak::ServiceKrishiSevak::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

KrishiSevak::ServiceKrishiSevak_ptr
KrishiSevak::ServiceKrishiSevak::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ServiceKrishiSevak _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ServiceKrishiSevak* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_ServiceKrishiSevak;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* KrishiSevak::ServiceKrishiSevak::_PD_repoId = "IDL:KrishiSevak/ServiceKrishiSevak:1.0";


KrishiSevak::_objref_ServiceKrishiSevak::~_objref_ServiceKrishiSevak() {
  
}


KrishiSevak::_objref_ServiceKrishiSevak::_objref_ServiceKrishiSevak(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::KrishiSevak::ServiceKrishiSevak::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
KrishiSevak::_objref_ServiceKrishiSevak::_ptrToObjRef(const char* id)
{
  if( id == ::KrishiSevak::ServiceKrishiSevak::_PD_repoId )
    return (::KrishiSevak::ServiceKrishiSevak_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::KrishiSevak::ServiceKrishiSevak::_PD_repoId) )
    return (::KrishiSevak::ServiceKrishiSevak_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_clong_n_clong_o_clong
class _0RL_cd_1e324afb4b44ba91_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1e324afb4b44ba91_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Long arg_1_;
  ::CORBA::Long* arg_1;
  ::CORBA::Long arg_2;
  ::CORBA::Boolean result;
};

void _0RL_cd_1e324afb4b44ba91_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  *arg_1 >>= _n;

}

void _0RL_cd_1e324afb4b44ba91_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  (::CORBA::Long&)arg_1_ <<= _n;
  arg_1 = &arg_1_;

}

void _0RL_cd_1e324afb4b44ba91_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  *arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_1e324afb4b44ba91_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  (::CORBA::Long&)*arg_1 <<= _n;
  (::CORBA::Long&)arg_2 <<= _n;

}

const char* const _0RL_cd_1e324afb4b44ba91_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1e324afb4b44ba91_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1e324afb4b44ba91_00000000* tcd = (_0RL_cd_1e324afb4b44ba91_00000000*)cd;
  KrishiSevak::_impl_ServiceKrishiSevak* impl = (KrishiSevak::_impl_ServiceKrishiSevak*) svnt->_ptrToInterface(KrishiSevak::ServiceKrishiSevak::_PD_repoId);
  tcd->result = impl->CallServiceRoutineA(tcd->arg_0, *tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean KrishiSevak::_objref_ServiceKrishiSevak::CallServiceRoutineA(::CORBA::Long num1, ::CORBA::Long& num2, ::CORBA::Long& retNum)
{
  _0RL_cd_1e324afb4b44ba91_00000000 _call_desc(_0RL_lcfn_1e324afb4b44ba91_10000000, "CallServiceRoutineA", 20);
  _call_desc.arg_0 = num1;
  _call_desc.arg_1 = &(::CORBA::Long&) num2;

  _invoke(_call_desc);
  retNum = _call_desc.arg_2;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_n_clong_n_clong
class _0RL_cd_1e324afb4b44ba91_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1e324afb4b44ba91_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0_;
  ::CORBA::Long* arg_0;
  ::CORBA::Long arg_1_;
  ::CORBA::Long* arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_1e324afb4b44ba91_20000000::marshalArguments(cdrStream& _n)
{
  *arg_0 >>= _n;
  *arg_1 >>= _n;

}

void _0RL_cd_1e324afb4b44ba91_20000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0_ <<= _n;
  arg_0 = &arg_0_;
  (::CORBA::Long&)arg_1_ <<= _n;
  arg_1 = &arg_1_;

}

void _0RL_cd_1e324afb4b44ba91_20000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  *arg_0 >>= _n;
  *arg_1 >>= _n;

}

void _0RL_cd_1e324afb4b44ba91_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  (::CORBA::Long&)*arg_0 <<= _n;
  (::CORBA::Long&)*arg_1 <<= _n;

}

const char* const _0RL_cd_1e324afb4b44ba91_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1e324afb4b44ba91_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1e324afb4b44ba91_20000000* tcd = (_0RL_cd_1e324afb4b44ba91_20000000*)cd;
  KrishiSevak::_impl_ServiceKrishiSevak* impl = (KrishiSevak::_impl_ServiceKrishiSevak*) svnt->_ptrToInterface(KrishiSevak::ServiceKrishiSevak::_PD_repoId);
  tcd->result = impl->CallServiceRoutineB(*tcd->arg_0, *tcd->arg_1);


}

::CORBA::Boolean KrishiSevak::_objref_ServiceKrishiSevak::CallServiceRoutineB(::CORBA::Long& num1, ::CORBA::Long& num2)
{
  _0RL_cd_1e324afb4b44ba91_20000000 _call_desc(_0RL_lcfn_1e324afb4b44ba91_30000000, "CallServiceRoutineB", 20);
  _call_desc.arg_0 = &(::CORBA::Long&) num1;
  _call_desc.arg_1 = &(::CORBA::Long&) num2;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_n_cstring
class _0RL_cd_1e324afb4b44ba91_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1e324afb4b44ba91_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  char** arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_1e324afb4b44ba91_40000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(*arg_1,0);

}

void _0RL_cd_1e324afb4b44ba91_40000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = &arg_1_.inout();

}

void _0RL_cd_1e324afb4b44ba91_40000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  _n.marshalString(*arg_1,0);

}

void _0RL_cd_1e324afb4b44ba91_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  arg_1_ = *arg_1;
  *arg_1 = (char*) _CORBA_String_helper::empty_string;
  *arg_1 = _n.unmarshalString(0);

}

const char* const _0RL_cd_1e324afb4b44ba91_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1e324afb4b44ba91_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1e324afb4b44ba91_40000000* tcd = (_0RL_cd_1e324afb4b44ba91_40000000*)cd;
  KrishiSevak::_impl_ServiceKrishiSevak* impl = (KrishiSevak::_impl_ServiceKrishiSevak*) svnt->_ptrToInterface(KrishiSevak::ServiceKrishiSevak::_PD_repoId);
  tcd->result = impl->CreateKrishiSevakProflie(tcd->arg_0, *tcd->arg_1);


}

::CORBA::Boolean KrishiSevak::_objref_ServiceKrishiSevak::CreateKrishiSevakProflie(const char* newProfile, ::CORBA::String_INOUT_arg returnmsg)
{
  _0RL_cd_1e324afb4b44ba91_40000000 _call_desc(_0RL_lcfn_1e324afb4b44ba91_50000000, "CreateKrishiSevakProflie", 25);
  _call_desc.arg_0 = newProfile;
  _call_desc.arg_1 = &(char*&) returnmsg;

  _invoke(_call_desc);
  return _call_desc.result;


}
KrishiSevak::_pof_ServiceKrishiSevak::~_pof_ServiceKrishiSevak() {}


omniObjRef*
KrishiSevak::_pof_ServiceKrishiSevak::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::KrishiSevak::_objref_ServiceKrishiSevak(ior, id);
}


::CORBA::Boolean
KrishiSevak::_pof_ServiceKrishiSevak::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::KrishiSevak::ServiceKrishiSevak::_PD_repoId) )
    return 1;
  
  return 0;
}

const KrishiSevak::_pof_ServiceKrishiSevak _the_pof_KrishiSevak_mServiceKrishiSevak;

KrishiSevak::_impl_ServiceKrishiSevak::~_impl_ServiceKrishiSevak() {}


::CORBA::Boolean
KrishiSevak::_impl_ServiceKrishiSevak::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "CallServiceRoutineA") ) {

    _0RL_cd_1e324afb4b44ba91_00000000 _call_desc(_0RL_lcfn_1e324afb4b44ba91_10000000, "CallServiceRoutineA", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "CallServiceRoutineB") ) {

    _0RL_cd_1e324afb4b44ba91_20000000 _call_desc(_0RL_lcfn_1e324afb4b44ba91_30000000, "CallServiceRoutineB", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "CreateKrishiSevakProflie") ) {

    _0RL_cd_1e324afb4b44ba91_40000000 _call_desc(_0RL_lcfn_1e324afb4b44ba91_50000000, "CreateKrishiSevakProflie", 25, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
KrishiSevak::_impl_ServiceKrishiSevak::_ptrToInterface(const char* id)
{
  if( id == ::KrishiSevak::ServiceKrishiSevak::_PD_repoId )
    return (::KrishiSevak::_impl_ServiceKrishiSevak*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::KrishiSevak::ServiceKrishiSevak::_PD_repoId) )
    return (::KrishiSevak::_impl_ServiceKrishiSevak*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
KrishiSevak::_impl_ServiceKrishiSevak::_mostDerivedRepoId()
{
  return ::KrishiSevak::ServiceKrishiSevak::_PD_repoId;
}

POA_KrishiSevak::ServiceKrishiSevak::~ServiceKrishiSevak() {}

