// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "KrishiSevak.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = "omniORB_4_1";



KrishiSevak::ServerKrishiSevak_ptr KrishiSevak::ServerKrishiSevak_Helper::_nil() {
  return ::KrishiSevak::ServerKrishiSevak::_nil();
}

::CORBA::Boolean KrishiSevak::ServerKrishiSevak_Helper::is_nil(::KrishiSevak::ServerKrishiSevak_ptr p) {
  return ::CORBA::is_nil(p);

}

void KrishiSevak::ServerKrishiSevak_Helper::release(::KrishiSevak::ServerKrishiSevak_ptr p) {
  ::CORBA::release(p);
}

void KrishiSevak::ServerKrishiSevak_Helper::marshalObjRef(::KrishiSevak::ServerKrishiSevak_ptr obj, cdrStream& s) {
  ::KrishiSevak::ServerKrishiSevak::_marshalObjRef(obj, s);
}

KrishiSevak::ServerKrishiSevak_ptr KrishiSevak::ServerKrishiSevak_Helper::unmarshalObjRef(cdrStream& s) {
  return ::KrishiSevak::ServerKrishiSevak::_unmarshalObjRef(s);
}

void KrishiSevak::ServerKrishiSevak_Helper::duplicate(::KrishiSevak::ServerKrishiSevak_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

KrishiSevak::ServerKrishiSevak_ptr
KrishiSevak::ServerKrishiSevak::_duplicate(::KrishiSevak::ServerKrishiSevak_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

KrishiSevak::ServerKrishiSevak_ptr
KrishiSevak::ServerKrishiSevak::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


KrishiSevak::ServerKrishiSevak_ptr
KrishiSevak::ServerKrishiSevak::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

KrishiSevak::ServerKrishiSevak_ptr
KrishiSevak::ServerKrishiSevak::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ServerKrishiSevak _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ServerKrishiSevak* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_ServerKrishiSevak;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* KrishiSevak::ServerKrishiSevak::_PD_repoId = "IDL:KrishiSevak/ServerKrishiSevak:1.0";


KrishiSevak::_objref_ServerKrishiSevak::~_objref_ServerKrishiSevak() {
  
}


KrishiSevak::_objref_ServerKrishiSevak::_objref_ServerKrishiSevak(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::KrishiSevak::ServerKrishiSevak::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
KrishiSevak::_objref_ServerKrishiSevak::_ptrToObjRef(const char* id)
{
  if( id == ::KrishiSevak::ServerKrishiSevak::_PD_repoId )
    return (::KrishiSevak::ServerKrishiSevak_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::KrishiSevak::ServerKrishiSevak::_PD_repoId) )
    return (::KrishiSevak::ServerKrishiSevak_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_clong_n_clong
class _0RL_cd_edd82261fe608293_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_edd82261fe608293_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Long arg_1_;
  ::CORBA::Long* arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_edd82261fe608293_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  *arg_1 >>= _n;

}

void _0RL_cd_edd82261fe608293_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  (::CORBA::Long&)arg_1_ <<= _n;
  arg_1 = &arg_1_;

}

void _0RL_cd_edd82261fe608293_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  *arg_1 >>= _n;

}

void _0RL_cd_edd82261fe608293_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  (::CORBA::Long&)*arg_1 <<= _n;

}

const char* const _0RL_cd_edd82261fe608293_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_edd82261fe608293_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_edd82261fe608293_00000000* tcd = (_0RL_cd_edd82261fe608293_00000000*)cd;
  KrishiSevak::_impl_ServerKrishiSevak* impl = (KrishiSevak::_impl_ServerKrishiSevak*) svnt->_ptrToInterface(KrishiSevak::ServerKrishiSevak::_PD_repoId);
  tcd->result = impl->CreateKrishiSevakProflie(tcd->arg_0, *tcd->arg_1);


}

::CORBA::Boolean KrishiSevak::_objref_ServerKrishiSevak::CreateKrishiSevakProflie(::CORBA::Long newprofile, ::CORBA::Long& exitStatus)
{
  _0RL_cd_edd82261fe608293_00000000 _call_desc(_0RL_lcfn_edd82261fe608293_10000000, "CreateKrishiSevakProflie", 25);
  _call_desc.arg_0 = newprofile;
  _call_desc.arg_1 = &(::CORBA::Long&) exitStatus;

  _invoke(_call_desc);
  return _call_desc.result;


}
KrishiSevak::_pof_ServerKrishiSevak::~_pof_ServerKrishiSevak() {}


omniObjRef*
KrishiSevak::_pof_ServerKrishiSevak::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::KrishiSevak::_objref_ServerKrishiSevak(ior, id);
}


::CORBA::Boolean
KrishiSevak::_pof_ServerKrishiSevak::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::KrishiSevak::ServerKrishiSevak::_PD_repoId) )
    return 1;
  
  return 0;
}

const KrishiSevak::_pof_ServerKrishiSevak _the_pof_KrishiSevak_mServerKrishiSevak;

KrishiSevak::_impl_ServerKrishiSevak::~_impl_ServerKrishiSevak() {}


::CORBA::Boolean
KrishiSevak::_impl_ServerKrishiSevak::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "CreateKrishiSevakProflie") ) {

    _0RL_cd_edd82261fe608293_00000000 _call_desc(_0RL_lcfn_edd82261fe608293_10000000, "CreateKrishiSevakProflie", 25, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
KrishiSevak::_impl_ServerKrishiSevak::_ptrToInterface(const char* id)
{
  if( id == ::KrishiSevak::ServerKrishiSevak::_PD_repoId )
    return (::KrishiSevak::_impl_ServerKrishiSevak*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::KrishiSevak::ServerKrishiSevak::_PD_repoId) )
    return (::KrishiSevak::_impl_ServerKrishiSevak*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
KrishiSevak::_impl_ServerKrishiSevak::_mostDerivedRepoId()
{
  return ::KrishiSevak::ServerKrishiSevak::_PD_repoId;
}

POA_KrishiSevak::ServerKrishiSevak::~ServerKrishiSevak() {}

